# Generated by Django 4.2.7 on 2023-11-19 04:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("escola", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aluno",
            name="sem",
        ),
        migrations.AlterField(
            model_name="curso",
            name="nivel",
            field=models.CharField(
                choices=[("B", "Básico"), ("I", "Intermediário"), ("A", "Avançado")],
                default="B",
                max_length=1,
            ),
        ),
    ]
