# Generated by Django 4.2.7 on 2023-11-19 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("escola", "0002_remove_aluno_sem_alter_curso_nivel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curso",
            name="nivel",
            field=models.CharField(
                choices=[("B", "Básico"), ("A", "Avançado"), ("I", "Intermediário")],
                default="B",
                max_length=1,
            ),
        ),
        migrations.CreateModel(
            name="Matricula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "periodo",
                    models.CharField(
                        choices=[("N", "Noite"), ("T", "Tarde"), ("M", "Manhã")],
                        default="M",
                        max_length=1,
                    ),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="escola.aluno"
                    ),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="escola.curso"
                    ),
                ),
            ],
        ),
    ]
