# Generated by Django 4.2.7 on 2023-11-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("escola", "0003_alter_curso_nivel_matricula"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curso",
            name="nivel",
            field=models.CharField(
                choices=[("I", "Intermediário"), ("B", "Básico"), ("A", "Avançado")],
                default="B",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="matricula",
            name="periodo",
            field=models.CharField(
                choices=[("N", "Noite"), ("M", "Manhã"), ("T", "Tarde")],
                default="M",
                max_length=1,
            ),
        ),
    ]
